apiVersion: v2
name: k8s-security
description: Network Policy, Pod Security and Zero Trust (Linkerd) hardening chart
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - security
  - network-policy 
  - pod-security
  - zero-trust
  - linkerd
maintainers:
  - name: hvvup

dependencies: 
  - name: linkerd-crds
    version: "1.8.0"
    repository: "https://helm.linkerd.io/stable"
    condition: zeroTrust.enabled

  - name: linkerd-control-plane
    version: "~1.16.0"
    repository: "https://helm.linkerd.io/stable"
    condition: zeroTrust.enabled