{{- if .Values.zeroTrust.enabled }}
{{- range .Values.zeroTrust.authorizationPolicy.allowedServices }}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: Server 
metadata:
  name: {{ .server }}-server
  namespace: {{ $.Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .server }}
  port: {{ (index .ports 0) }}
  proxyProtocol: HTTP/2
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: {{ .server }}-server
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: MeshTLSAuthentication
      name: {{ .client.serviceAccount }}-authn 
---
apiVersion: policy.linkerd.io/v1alpha1 
kind: MeshTLSAuthentication
metadata:
  name: {{ .client.serviceAccount }}-authn 
  namespace: {{$.Values.namespace }}
spec: 
  identities:
    - "{{ .client.serviceAccount }}.{{ $.Values.namespace }}.serviceaccount.identity.linkerd.cluster.local"
{{- end }}
{{- if .Values.zeroTrust.authorizationPolicy.defaultDeny }}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: Server
metadata:
  name: default-deny 
  namespace: {{ .Values.namespace }}
  annotations:
    policy.linkerd.io/default-allow: "deny"
spec:
  podSelector:
    matchLabels: {}
{{- end }}
{{- end }}